// Package main 是 registerTools 代码生成器：扫描 internal/tools 目录，
// 按目录名排序生成 internal/app/tools_gen.go 中的注册函数。
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "toolsgen:", err)
		os.Exit(1)
	}
}

func run() error {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return fmt.Errorf("无法定位生成器路径")
	}
	root := filepath.Dir(filepath.Dir(filepath.Dir(file))) // internal/toolsgen/main.go -> 仓库根
	toolsDir := filepath.Join(root, "internal", "tools")
	entries, err := os.ReadDir(toolsDir)
	if err != nil {
		return fmt.Errorf("读取 %s 失败: %w", toolsDir, err)
	}

	type toolPkg struct {
		dirName string
		pkgName string
	}
	var pkgs []toolPkg
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkgName, err := detectPackage(filepath.Join(toolsDir, e.Name()))
		if err != nil {
			return fmt.Errorf("%s: %w", e.Name(), err)
		}
		pkgs = append(pkgs, toolPkg{dirName: e.Name(), pkgName: pkgName})
	}
	// 按目录名排序（os.ReadDir 已排序，此处显式保证）。
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].dirName < pkgs[j].dirName })

	// 校验包名无冲突。
	seen := map[string]string{}
	for _, p := range pkgs {
		if prev, dup := seen[p.pkgName]; dup {
			return fmt.Errorf("包名冲突: %s 与 %s 都是 %s", prev, p.dirName, p.pkgName)
		}
		seen[p.pkgName] = p.dirName
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by internal/toolsgen; DO NOT EDIT.\n\n")
	sb.WriteString("package app\n\n")
	sb.WriteString("import (\n")
	for _, p := range pkgs {
		fmt.Fprintf(&sb, "\t%s %q\n", p.pkgName, "it-tools-go/internal/tools/"+p.dirName)
	}
	sb.WriteString("\t\"it-tools-go/internal/registry\"\n")
	sb.WriteString(")\n\n")
	sb.WriteString("// registerAllTools 注册全部工具（顺序为 internal/tools 目录名排序）。\n")
	sb.WriteString("func registerAllTools(reg *registry.Registry) {\n")
	for _, p := range pkgs {
		fmt.Fprintf(&sb, "\treg.Register(%s.Tool(), %s.Executor{})\n", p.pkgName, p.pkgName)
	}
	sb.WriteString("}\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("格式化生成代码失败: %w", err)
	}

	outFile := filepath.Join(root, "internal", "app", "tools_gen.go")
	if err := os.WriteFile(outFile, formatted, 0o644); err != nil {
		return fmt.Errorf("写入 %s 失败: %w", outFile, err)
	}
	fmt.Printf("toolsgen: 已生成 %s（%d 个工具）\n", outFile, len(pkgs))
	return nil
}

var pkgRe = regexp.MustCompile(`(?m)^package\s+(\w+)\s*$`)

// detectPackage 读取目录内首个非 _test.go 的 .go 文件，返回其包名并校验 Tool/Executor 契约。
func detectPackage(dir string) (string, error) {
	names, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	for _, n := range names {
		if n.IsDir() || !strings.HasSuffix(n.Name(), ".go") || strings.HasSuffix(n.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, n.Name()))
		if err != nil {
			return "", err
		}
		m := pkgRe.FindSubmatch(data)
		if m == nil {
			return "", fmt.Errorf("无法解析 %s 的 package 声明", n.Name())
		}
		src := string(data)
		if !strings.Contains(src, "func Tool()") {
			return "", fmt.Errorf("%s 缺少 func Tool()", n.Name())
		}
		if !strings.Contains(src, "type Executor") {
			return "", fmt.Errorf("%s 缺少 type Executor", n.Name())
		}
		return string(m[1]), nil
	}
	return "", fmt.Errorf("目录中无 Go 源文件")
}
