package httpstatuscodes

// codesByCategories 内置 HTTP 状态码表（按分类组织），数据移植自 it-tools（GPLv3）。
var codesByCategories = []CodeCategory{
	{
		Category: "1xx informational response",
		Codes: []StatusCode{
			{100, "Continue", "Waiting for the client to emit the body of the request.", "HTTP"},
			{101, "Switching Protocols", "The server has agreed to change protocol.", "HTTP"},
			{102, "Processing", "The server is processing the request, but no response is available yet.", "WebDav"},
			{103, "Early Hints", "The server returns some response headers before final HTTP message.", "HTTP"},
		},
	},
	{
		Category: "2xx success",
		Codes: []StatusCode{
			{200, "OK", "Standard response for successful HTTP requests.", "HTTP"},
			{201, "Created", "The request has been fulfilled, resulting in the creation of a new resource.", "HTTP"},
			{202, "Accepted", "The request has been accepted for processing, but the processing has not been completed.", "HTTP"},
			{203, "Non-Authoritative Information", "The request is successful but the content of the original request has been modified by a transforming proxy.", "HTTP"},
			{204, "No Content", "The server successfully processed the request and is not returning any content.", "HTTP"},
			{205, "Reset Content", "The server indicates to reinitialize the document view which sent this request.", "HTTP"},
			{206, "Partial Content", "The server is delivering only part of the resource due to a range header sent by the client.", "HTTP"},
			{207, "Multi-Status", "The message body that follows is an XML message and can contain a number of separate response codes.", "WebDav"},
			{208, "Already Reported", "The members of a DAV binding have already been enumerated in a preceding part of the (multistatus) response.", "WebDav"},
			{226, "IM Used", "The server has fulfilled a request for the resource, and the response is a representation of the result.", "HTTP"},
		},
	},
	{
		Category: "3xx redirection",
		Codes: []StatusCode{
			{300, "Multiple Choices", "Indicates multiple options for the resource that the client may follow.", "HTTP"},
			{301, "Moved Permanently", "This and all future requests should be directed to the given URI.", "HTTP"},
			{302, "Found", "Redirect to another URL. This is an example of industry practice contradicting the standard.", "HTTP"},
			{303, "See Other", "The response to the request can be found under another URI using a GET method.", "HTTP"},
			{304, "Not Modified", "Indicates that the resource has not been modified since the version specified by the request headers.", "HTTP"},
			{305, "Use Proxy", "The requested resource is available only through a proxy, the address for which is provided in the response.", "HTTP"},
			{306, "Switch Proxy", "No longer used. Originally meant \"Subsequent requests should use the specified proxy.\"", "HTTP"},
			{307, "Temporary Redirect", "In this case, the request should be repeated with another URI; however, future requests should still use the original URI.", "HTTP"},
			{308, "Permanent Redirect", "The request and all future requests should be repeated using another URI.", "HTTP"},
		},
	},
	{
		Category: "4xx client error",
		Codes: []StatusCode{
			{400, "Bad Request", "The server cannot or will not process the request due to an apparent client error.", "HTTP"},
			{401, "Unauthorized", "Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided.", "HTTP"},
			{402, "Payment Required", "Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme.", "HTTP"},
			{403, "Forbidden", "The request was valid, but the server is refusing action. The user might not have the necessary permissions for a resource.", "HTTP"},
			{404, "Not Found", "The requested resource could not be found but may be available in the future.", "HTTP"},
			{405, "Method Not Allowed", "A request method is not supported for the requested resource.", "HTTP"},
			{406, "Not Acceptable", "The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.", "HTTP"},
			{407, "Proxy Authentication Required", "The client must first authenticate itself with the proxy.", "HTTP"},
			{408, "Request Timeout", "The server timed out waiting for the request.", "HTTP"},
			{409, "Conflict", "Indicates that the request could not be processed because of conflict in the request, such as an edit conflict.", "HTTP"},
			{410, "Gone", "Indicates that the resource requested is no longer available and will not be available again.", "HTTP"},
			{411, "Length Required", "The request did not specify the length of its content, which is required by the requested resource.", "HTTP"},
			{412, "Precondition Failed", "The server does not meet one of the preconditions that the requester put on the request.", "HTTP"},
			{413, "Payload Too Large", "The request is larger than the server is willing or able to process.", "HTTP"},
			{414, "URI Too Long", "The URI provided was too long for the server to process.", "HTTP"},
			{415, "Unsupported Media Type", "The request entity has a media type which the server or resource does not support.", "HTTP"},
			{416, "Range Not Satisfiable", "The client has asked for a portion of the file, but the server cannot supply that portion.", "HTTP"},
			{417, "Expectation Failed", "The server cannot meet the requirements of the Expect request-header field.", "HTTP"},
			{418, "I'm a teapot", "The server refuses the attempt to brew coffee with a teapot.", "HTTP"},
			{421, "Misdirected Request", "The request was directed at a server that is not able to produce a response.", "HTTP"},
			{422, "Unprocessable Entity", "The request was well-formed but was unable to be followed due to semantic errors.", "HTTP"},
			{423, "Locked", "The resource that is being accessed is locked.", "HTTP"},
			{424, "Failed Dependency", "The request failed due to failure of a previous request.", "HTTP"},
			{425, "Too Early", "Indicates that the server is unwilling to risk processing a request that might be replayed.", "HTTP"},
			{426, "Upgrade Required", "The client should switch to a different protocol such as TLS/1.0.", "HTTP"},
			{428, "Precondition Required", "The origin server requires the request to be conditional.", "HTTP"},
			{429, "Too Many Requests", "The user has sent too many requests in a given amount of time.", "HTTP"},
			{431, "Request Header Fields Too Large", "The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.", "HTTP"},
			{451, "Unavailable For Legal Reasons", "A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource.", "HTTP"},
		},
	},
	{
		Category: "5xx server error",
		Codes: []StatusCode{
			{500, "Internal Server Error", "A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.", "HTTP"},
			{501, "Not Implemented", "The server either does not recognize the request method, or it lacks the ability to fulfill the request.", "HTTP"},
			{502, "Bad Gateway", "The server was acting as a gateway or proxy and received an invalid response from the upstream server.", "HTTP"},
			{503, "Service Unavailable", "The server is currently unavailable (because it is overloaded or down for maintenance).", "HTTP"},
			{504, "Gateway Timeout", "The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.", "HTTP"},
			{505, "HTTP Version Not Supported", "The server does not support the HTTP protocol version used in the request.", "HTTP"},
			{506, "Variant Also Negotiates", "Transparent content negotiation for the request results in a circular reference.", "HTTP"},
			{507, "Insufficient Storage", "The server is unable to store the representation needed to complete the request.", "HTTP"},
			{508, "Loop Detected", "The server detected an infinite loop while processing the request.", "HTTP"},
			{510, "Not Extended", "Further extensions to the request are required for the server to fulfill it.", "HTTP"},
			{511, "Network Authentication Required", "The client needs to authenticate to gain network access.", "HTTP"},
		},
	},
}