// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {registry} from '../models';

export function ListTools():Promise<Array<registry.Tool>>;

export function RunTool(arg1:string,arg2:string):Promise<string>;
