// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListTools() {
  return window['go']['app']['App']['ListTools']();
}

export function RunTool(arg1, arg2) {
  return window['go']['app']['App']['RunTool'](arg1, arg2);
}
